SECTIONS = [
    "<[Year Founded]>",
    "<[City State]>",
    "<[AUM]>",
    "<[Manager Type: New/Existing]>",
    "<[Original Source]>",
    "<[Firm Overview]>",
    "<[Fundraise Summary & Timing]>",
    "<[Diligence Items]>",
    "<[Conclusions]>",
    "<[Overview]>",
    "<[Market Opportunity]>",
    "<[Differentiation & Winning Deals]>",
    "<[Sourcing & Picking Deals]>",
    "<[Post-Investment]>",
    "<[Exiting Deals]>",
    "<[Portfolio Construction - Geography]>",
    "<[Portfolio Construction - number of companies]>",
    "<[Portfolio Construction - initial investment]>",
    "<[Portfolio Construction - Total Investment]>",
    "<[Portfolio Construction - Ownership Strategy]>",
    "<[Portfolio Construction - Entry Round]>",
    "<[Portfolio Construction - Reserve Strategy]>",
    "<[Portfolio Construction - Board Seats]>",
    "<[Initial Portfolio Investments]>",
    "<[Prior Track Record]>",
    "<[Similar Fund Managers]>",
    "<[Fund Team]>",
    "<[Co-Investment Views]>",
    "<[KWI Portfolio Overlap]>",
    "<[Network Reference Points]>"
]